# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutWidget(object):
    def setupUi(self, aboutWidget):
        aboutWidget.setObjectName("aboutWidget")
        aboutWidget.resize(700, 381)
        aboutWidget.setMaximumSize(QtCore.QSize(700, 700))
        aboutWidget.setStyleSheet("QWidget#aboutWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    color:black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(aboutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fireCanvasThumbNail = QtWidgets.QLabel(aboutWidget)
        self.fireCanvasThumbNail.setMaximumSize(QtCore.QSize(900, 900))
        self.fireCanvasThumbNail.setText("")
        self.fireCanvasThumbNail.setPixmap(QtGui.QPixmap("../assets/aboutThumbnail.png"))
        self.fireCanvasThumbNail.setObjectName("fireCanvasThumbNail")
        self.verticalLayout.addWidget(self.fireCanvasThumbNail, 0, QtCore.Qt.AlignHCenter)
        self.aboutText = QtWidgets.QLabel(aboutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutText.sizePolicy().hasHeightForWidth())
        self.aboutText.setSizePolicy(sizePolicy)
        self.aboutText.setMinimumSize(QtCore.QSize(0, 100))
        self.aboutText.setWordWrap(True)
        self.aboutText.setObjectName("aboutText")
        self.verticalLayout.addWidget(self.aboutText)
        self.licenseText = QtWidgets.QLabel(aboutWidget)
        self.licenseText.setObjectName("licenseText")
        self.verticalLayout.addWidget(self.licenseText)
        self.contactsText = QtWidgets.QLabel(aboutWidget)
        self.contactsText.setObjectName("contactsText")
        self.verticalLayout.addWidget(self.contactsText)

        self.retranslateUi(aboutWidget)
        QtCore.QMetaObject.connectSlotsByName(aboutWidget)

    def retranslateUi(self, aboutWidget):
        _translate = QtCore.QCoreApplication.translate
        aboutWidget.setWindowTitle(_translate("aboutWidget", "Form"))
        self.aboutText.setText(_translate("aboutWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">FireCanvas</span><span style=\" font-size:16pt;\"> is an Air to Air Drawing or Presentation Tool/Utility Build using PyQt5 and OpenCV (Currently in Alpha States)</span></p></body></html>"))
        self.licenseText.setText(_translate("aboutWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">License Type: </span><span style=\" font-size:14pt;\">GNU General Public License, version 2</span></p></body></html>"))
        self.contactsText.setText(_translate("aboutWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Contacts :</span><span style=\" font-size:14pt;\"> help@firecanvas.io, firecanvas.io,firecanvas@twitter</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aboutWidget = QtWidgets.QWidget()
    ui = Ui_aboutWidget()
    ui.setupUi(aboutWidget)
    aboutWidget.show()
    sys.exit(app.exec_())
