# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BoardPaneWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_boardPane(object):
    def setupUi(self, boardPane):
        boardPane.setObjectName("boardPane")
        boardPane.resize(960, 350)
        boardPane.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(boardPane)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uidesignFrame = QtWidgets.QFrame(boardPane)
        self.uidesignFrame.setObjectName("uidesignFrame")
        self.uidesignVBox = QtWidgets.QVBoxLayout(self.uidesignFrame)
        self.uidesignVBox.setObjectName("uidesignVBox")
        self.imgLabelUIDesgin = QtWidgets.QLabel(self.uidesignFrame)
        self.imgLabelUIDesgin.setMinimumSize(QtCore.QSize(300, 300))
        self.imgLabelUIDesgin.setMaximumSize(QtCore.QSize(300, 300))
        self.imgLabelUIDesgin.setText("")
        self.imgLabelUIDesgin.setPixmap(QtGui.QPixmap("../assets/UiDesignThumbNail.png"))
        self.imgLabelUIDesgin.setScaledContents(True)
        self.imgLabelUIDesgin.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabelUIDesgin.setWordWrap(False)
        self.imgLabelUIDesgin.setObjectName("imgLabelUIDesgin")
        self.uidesignVBox.addWidget(self.imgLabelUIDesgin, 0, QtCore.Qt.AlignHCenter)
        self.uiDesginPBtn = QtWidgets.QPushButton(self.uidesignFrame)
        self.uiDesginPBtn.setObjectName("uiDesginPBtn")
        self.uidesignVBox.addWidget(self.uiDesginPBtn)
        self.horizontalLayout.addWidget(self.uidesignFrame)
        self.simpleDrawingFrame_2 = QtWidgets.QFrame(boardPane)
        self.simpleDrawingFrame_2.setObjectName("simpleDrawingFrame_2")
        self.simpleDrawingFrame = QtWidgets.QVBoxLayout(self.simpleDrawingFrame_2)
        self.simpleDrawingFrame.setObjectName("simpleDrawingFrame")
        self.imgLabelSimpleDrawing = QtWidgets.QLabel(self.simpleDrawingFrame_2)
        self.imgLabelSimpleDrawing.setMinimumSize(QtCore.QSize(300, 300))
        self.imgLabelSimpleDrawing.setMaximumSize(QtCore.QSize(300, 300))
        self.imgLabelSimpleDrawing.setText("")
        self.imgLabelSimpleDrawing.setPixmap(QtGui.QPixmap("../assets/SimpleDrawingThumbnail.png"))
        self.imgLabelSimpleDrawing.setScaledContents(True)
        self.imgLabelSimpleDrawing.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabelSimpleDrawing.setWordWrap(False)
        self.imgLabelSimpleDrawing.setObjectName("imgLabelSimpleDrawing")
        self.simpleDrawingFrame.addWidget(self.imgLabelSimpleDrawing, 0, QtCore.Qt.AlignHCenter)
        self.simpleDrawingPBtn = QtWidgets.QPushButton(self.simpleDrawingFrame_2)
        self.simpleDrawingPBtn.setObjectName("simpleDrawingPBtn")
        self.simpleDrawingFrame.addWidget(self.simpleDrawingPBtn)
        self.horizontalLayout.addWidget(self.simpleDrawingFrame_2)
        self.whiteBoardFrame = QtWidgets.QFrame(boardPane)
        self.whiteBoardFrame.setObjectName("whiteBoardFrame")
        self.whiteboardVBox = QtWidgets.QVBoxLayout(self.whiteBoardFrame)
        self.whiteboardVBox.setObjectName("whiteboardVBox")
        self.imgLabelWhiteBoard = QtWidgets.QLabel(self.whiteBoardFrame)
        self.imgLabelWhiteBoard.setMinimumSize(QtCore.QSize(300, 300))
        self.imgLabelWhiteBoard.setMaximumSize(QtCore.QSize(300, 300))
        self.imgLabelWhiteBoard.setText("")
        self.imgLabelWhiteBoard.setPixmap(QtGui.QPixmap("../assets/WhiteBoardThumbNail.png"))
        self.imgLabelWhiteBoard.setScaledContents(True)
        self.imgLabelWhiteBoard.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabelWhiteBoard.setWordWrap(False)
        self.imgLabelWhiteBoard.setObjectName("imgLabelWhiteBoard")
        self.whiteboardVBox.addWidget(self.imgLabelWhiteBoard, 0, QtCore.Qt.AlignHCenter)
        self.whiteBoardPBtn = QtWidgets.QPushButton(self.whiteBoardFrame)
        self.whiteBoardPBtn.setObjectName("whiteBoardPBtn")
        self.whiteboardVBox.addWidget(self.whiteBoardPBtn)
        self.horizontalLayout.addWidget(self.whiteBoardFrame)

        self.retranslateUi(boardPane)
        QtCore.QMetaObject.connectSlotsByName(boardPane)

    def retranslateUi(self, boardPane):
        _translate = QtCore.QCoreApplication.translate
        boardPane.setWindowTitle(_translate("boardPane", "Form"))
        self.uiDesginPBtn.setText(_translate("boardPane", "UI Design"))
        self.simpleDrawingPBtn.setText(_translate("boardPane", "SimpleDrawing"))
        self.whiteBoardPBtn.setText(_translate("boardPane", "WhiteBoard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    boardPane = QtWidgets.QWidget()
    ui = Ui_boardPane()
    ui.setupUi(boardPane)
    boardPane.show()
    sys.exit(app.exec_())
