# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FloatingColorSelectionComponent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 10, 261, 251))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QLabel#colorControlBtn{\n"
"border-radius:100px;;\n"
"}")
        self.page.setObjectName("page")
        self.rainbowBGControl = QtWidgets.QLabel(self.page)
        self.rainbowBGControl.setGeometry(QtCore.QRect(10, 20, 231, 231))
        self.rainbowBGControl.setSizeIncrement(QtCore.QSize(200, 200))
        self.rainbowBGControl.setAutoFillBackground(False)
        # self.rainbowBGControl.setStyleSheet("QLabel:hover{\nbox-shadow:black 10px 10px 10px;}\n")
        self.rainbowBGControl.setText("")
        self.rainbowBGControl.setPixmap(QtGui.QPixmap("../assets/rainbowCircle.png"))
        self.rainbowBGControl.setScaledContents(True)
        self.rainbowBGControl.setObjectName("rainbowBGControl")
        self.colorControlBtn = QtWidgets.QPushButton(self.page)
        self.colorControlBtn.setGeometry(QtCore.QRect(80, 90, 81, 81))
        self.colorControlBtn.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 40px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.colorControlBtn.setObjectName("colorControlBtn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Floating Color Selection Component"))
        self.colorControlBtn.setIcon(QtGui.QIcon("../assets/paintBrushIcon.png"))
        self.colorControlBtn.setIconSize(QtCore.QSize(80,80))
        graphic = (QtWidgets.QGraphicsDropShadowEffect())
        graphic.setBlurRadius(100)
        graphic.setOffset(20)
        self.colorControlBtn.setGraphicsEffect(graphic)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
