# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecentlySavedWid.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recentlySavedFrame(object):
    def setupUi(self, recentlySavedFrame):
        recentlySavedFrame.setObjectName("recentlySavedFrame")
        recentlySavedFrame.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(recentlySavedFrame.sizePolicy().hasHeightForWidth())
        recentlySavedFrame.setSizePolicy(sizePolicy)
        recentlySavedFrame.setToolTip("")
        recentlySavedFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        recentlySavedFrame.setStyleSheet("QFrame#indexInfo{\n"
"    background-color: rgb(242, 242, 242);\n"
"}\n"
"QLabel{\n"
"    color:black;\n"
"}\n"
"QFrame{\n"
"    background-color:white;\n"
"}\n"
"QWidget#recentlySavedFrame{\n"
"    background-color:white;\n"
"}\n"
"QLabel{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"QLabel:hover{\n"
"    text-decoration: underline;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(recentlySavedFrame)
        self.verticalLayout.setContentsMargins(40, -1, 40, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.indexInfo = QtWidgets.QFrame(recentlySavedFrame)
        self.indexInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.indexInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.indexInfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.indexInfo.setObjectName("indexInfo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.indexInfo)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoIcon = QtWidgets.QLabel(self.indexInfo)
        self.infoIcon.setMaximumSize(QtCore.QSize(25, 25))
        self.infoIcon.setText("")
        self.infoIcon.setTextFormat(QtCore.Qt.AutoText)
        self.infoIcon.setPixmap(QtGui.QPixmap("../assets/infoIcon.png"))
        self.infoIcon.setScaledContents(True)
        self.infoIcon.setObjectName("infoIcon")
        self.horizontalLayout.addWidget(self.infoIcon)
        self.infoLabel = QtWidgets.QLabel(self.indexInfo)
        self.infoLabel.setAutoFillBackground(False)
        self.infoLabel.setObjectName("infoLabel")
        self.horizontalLayout.addWidget(self.infoLabel, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.indexInfo)
        self.filePath1 = QtWidgets.QFrame(recentlySavedFrame)
        self.filePath1.setEnabled(False)
        self.filePath1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.filePath1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filePath1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.filePath1.setObjectName("filePath1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.filePath1)
        self.horizontalLayout_3.setSpacing(40)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.folderIconLabel = QtWidgets.QLabel(self.filePath1)
        self.folderIconLabel.setMaximumSize(QtCore.QSize(34, 30))
        self.folderIconLabel.setText("")
        self.folderIconLabel.setPixmap(QtGui.QPixmap("../assets/Folder-open.png"))
        self.folderIconLabel.setScaledContents(True)
        self.folderIconLabel.setObjectName("folderIconLabel")
        self.horizontalLayout_3.addWidget(self.folderIconLabel, 0, QtCore.Qt.AlignLeft)
        self.folderNameLabel = QtWidgets.QLabel(self.filePath1)
        self.folderNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.folderNameLabel.setObjectName("folderNameLabel")
        self.horizontalLayout_3.addWidget(self.folderNameLabel, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.filePath1, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(recentlySavedFrame)
        QtCore.QMetaObject.connectSlotsByName(recentlySavedFrame)

    def retranslateUi(self, recentlySavedFrame):
        _translate = QtCore.QCoreApplication.translate
        recentlySavedFrame.setWindowTitle(_translate("recentlySavedFrame", "Form"))
        self.infoLabel.setText(_translate("recentlySavedFrame", "Empty! Nothing to see here"))
        self.folderNameLabel.setText(_translate("recentlySavedFrame", "No Folders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recentlySavedFrame = QtWidgets.QWidget()
    ui = Ui_recentlySavedFrame()
    ui.setupUi(recentlySavedFrame)
    recentlySavedFrame.show()
    sys.exit(app.exec_())
