# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimpleDrawingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_simpleDrawingWindow(object):
    def setupUi(self, simpleDrawingWindow):
        simpleDrawingWindow.setObjectName("simpleDrawingWindow")
        simpleDrawingWindow.resize(717, 454)
        simpleDrawingWindow.setStyleSheet("QPushButton{\n"
"    height:30px;\n"
"    background-color: rgb(42, 41, 160);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(simpleDrawingWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame = QtWidgets.QFrame(simpleDrawingWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modesBtn = QtWidgets.QPushButton(self.horizontalFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/modeBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modesBtn.setIcon(icon)
        self.modesBtn.setObjectName("modesBtn")
        self.horizontalLayout.addWidget(self.modesBtn)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalFrame_2.setStyleSheet("QPushButton{\n"
"    margin:0;\n"
"    border-radius:0px;\n"
"    background-color: rgb(51, 51, 51);\n"
"    width:100px;\n"
"    height:40px;\n"
"}")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.toolPane = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.toolPane.setContentsMargins(2, 2, 2, 2)
        self.toolPane.setSpacing(3)
        self.toolPane.setObjectName("toolPane")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.toolPane.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../assets/penIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.toolPane.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../assets/textSelectionIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolPane.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.horizontalFrame_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../assets/uploadBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../assets/exportBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.toolButton = QtWidgets.QToolButton(self.horizontalFrame)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.verticalStackedWidget = QtWidgets.QStackedWidget(simpleDrawingWindow)
        self.verticalStackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.verticalStackedWidget.setMouseTracking(True)
        self.verticalStackedWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalStackedWidget.setStyleSheet("")
        self.verticalStackedWidget.setObjectName("verticalStackedWidget")
        self.verticalStackedWidgetPage1 = QtWidgets.QWidget()
        self.verticalStackedWidgetPage1.setObjectName("verticalStackedWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalStackedWidgetPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalStackedWidget.addWidget(self.verticalStackedWidgetPage1)
        self.verticalLayout_2.addWidget(self.verticalStackedWidget)

        self.retranslateUi(simpleDrawingWindow)
        QtCore.QMetaObject.connectSlotsByName(simpleDrawingWindow)

    def retranslateUi(self, simpleDrawingWindow):
        _translate = QtCore.QCoreApplication.translate
        simpleDrawingWindow.setWindowTitle(_translate("simpleDrawingWindow", "Form"))
        self.modesBtn.setText(_translate("simpleDrawingWindow", "Modes"))
        self.pushButton_3.setText(_translate("simpleDrawingWindow", "Size"))
        self.pushButton_4.setText(_translate("simpleDrawingWindow", "Color"))
        self.pushButton_2.setText(_translate("simpleDrawingWindow", "T"))
        self.pushButton.setText(_translate("simpleDrawingWindow", "Upload"))
        self.pushButton_5.setText(_translate("simpleDrawingWindow", "Export"))
        self.toolButton.setText(_translate("simpleDrawingWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    simpleDrawingWindow = QtWidgets.QWidget()
    ui = Ui_simpleDrawingWindow()
    ui.setupUi(simpleDrawingWindow)
    simpleDrawingWindow.show()
    sys.exit(app.exec_())
